services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cinehub-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # RabbitMQ dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: cinehub-redis
    command: ["redis-server", "--notify-keyspace-events", "KEA"]
    ports:
      - "6379:6379"

  auth-service:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    container_name: auth-service
    ports:
      - "8081:8081"

  user-profile-service:
    build: ./services/user-profile-service
    env_file:
      - ./services/user-profile-service/.env
    container_name: user-profile-service
    ports:
      - "8082:8082"

  movie-service:
    build: ./services/movie-service
    env_file:
      - ./services/movie-service/.env
    container_name: movie-service
    ports:
      - "8083:8083"

  showtime-service:
    build: ./services/showtime-service
    env_file:
      - ./services/showtime-service/.env
    container_name: showtime-service
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
      - redis

  booking-service:
    build: ./services/booking-service
    env_file:
      - ./services/booking-service/.env
    container_name: booking-service
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - showtime-service
      - pricing-service
      - promotion-service
      - fnb-service
      - user-profile-service

  payment-service:
    build: ./services/payment-service
    env_file:
      - ./services/payment-service/.env
    container_name: payment-service
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq

  pricing-service:
    build: ./services/pricing-service
    env_file:
      - ./services/pricing-service/.env
    container_name: pricing-service
    ports:
      - "8087:8087"

  fnb-service:
    build: ./services/fnb-service
    env_file:
      - ./services/fnb-service/.env
    container_name: fnb-service
    ports:
      - "8088:8088"

  promotion-service:
    build: ./services/promotion-service
    env_file:
      - ./services/promotion-service/.env
    container_name: promotion-service
    ports:
      - "8089:8089"

  notification-service:
    build: ./services/notification-service
    env_file:
      - ./services/notification-service/.env
    container_name: notification-service
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq

  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "8099:8099"
    depends_on:
      - auth-service
      - user-profile-service
      - movie-service
      - showtime-service
      - booking-service
      - payment-service
      - pricing-service
      - fnb-service
      - promotion-service
      - notification-service
